// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/zeshi09/go_web_parser_agent/ent/runtime.go

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
