// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/zeshi09/go_web_parser_agent/ent/domain"
	"github.com/zeshi09/go_web_parser_agent/ent/schema"
	"github.com/zeshi09/go_web_parser_agent/ent/sociallink"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	domainFields := schema.Domain{}.Fields()
	_ = domainFields
	// domainDescCreatedAt is the schema descriptor for created_at field.
	domainDescCreatedAt := domainFields[1].Descriptor()
	// domain.DefaultCreatedAt holds the default value on creation for the created_at field.
	domain.DefaultCreatedAt = domainDescCreatedAt.Default.(func() time.Time)
	sociallinkFields := schema.SocialLink{}.Fields()
	_ = sociallinkFields
	// sociallinkDescCreatedAt is the schema descriptor for created_at field.
	sociallinkDescCreatedAt := sociallinkFields[2].Descriptor()
	// sociallink.DefaultCreatedAt holds the default value on creation for the created_at field.
	sociallink.DefaultCreatedAt = sociallinkDescCreatedAt.Default.(func() time.Time)
}
