// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zeshi09/go_web_parser_agent/ent/sociallink"
)

// SocialLinkCreate is the builder for creating a SocialLink entity.
type SocialLinkCreate struct {
	config
	mutation *SocialLinkMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *SocialLinkCreate) SetURL(v string) *SocialLinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *SocialLinkCreate) SetDomain(v string) *SocialLinkCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *SocialLinkCreate) SetNillableDomain(v *string) *SocialLinkCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SocialLinkCreate) SetCreatedAt(v time.Time) *SocialLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SocialLinkCreate) SetNillableCreatedAt(v *time.Time) *SocialLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SocialLinkMutation object of the builder.
func (_c *SocialLinkCreate) Mutation() *SocialLinkMutation {
	return _c.mutation
}

// Save creates the SocialLink in the database.
func (_c *SocialLinkCreate) Save(ctx context.Context) (*SocialLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SocialLinkCreate) SaveX(ctx context.Context) *SocialLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SocialLinkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sociallink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SocialLinkCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "SocialLink.url"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SocialLink.created_at"`)}
	}
	return nil
}

func (_c *SocialLinkCreate) sqlSave(ctx context.Context) (*SocialLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SocialLinkCreate) createSpec() (*SocialLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SocialLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sociallink.Table, sqlgraph.NewFieldSpec(sociallink.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(sociallink.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(sociallink.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sociallink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SocialLinkCreateBulk is the builder for creating many SocialLink entities in bulk.
type SocialLinkCreateBulk struct {
	config
	err      error
	builders []*SocialLinkCreate
}

// Save creates the SocialLink entities in the database.
func (_c *SocialLinkCreateBulk) Save(ctx context.Context) ([]*SocialLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SocialLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SocialLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SocialLinkCreateBulk) SaveX(ctx context.Context) []*SocialLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
